# Generated by Django 6.0.7 on 2026-08-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_add_price_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
