# Generated by Django 6.0.7 on 2026-08-16 22:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='content',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
