# Generated by Django 6.0.7 on 2026-08-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_aboutpage_content_aboutpage_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('subject', models.CharField(choices=[('formation', 'Inscription à une Formation'), ('service', 'Demande de Service Créatif / Tech'), ('produit', 'Achat de Produit Digital'), ('autre', 'Autre')], default='service', max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
